ubilabs/esa-climate-from-space

- src/scripts/components/story-video/story-video.tsx
- storage/stories/story2/story2-de.json
- storage/stories/story2/story2-en.json
> feat(video): add test video with subtitles

- scripts/slack-deployment-notification.js
> chore(slack-notification): only show first line of commit message

- src/scripts/components/data-set-info/data-set-info.styl
- src/scripts/components/data-set-info/data-set-info.tsx
- src/scripts/components/globe-navigation/globe-navigation.styl
- src/scripts/components/info-button/info-button.tsx
- src/scripts/components/layer-selector/layer-selector.styl
- src/scripts/components/overlay/overlay.styl
- src/scripts/components/time-slider/time-slider.styl
- src/scripts/components/time-slider/time-slider.tsx
> refactor(slider): implement new slider design

- src/scripts/components/story-video/story-video.tsx
> feat(video): set subtitle language

- src/scripts/hooks/use-slide.ts
> fix(globe): only show globes that are set by story slides

- src/scripts/components/story-footer/story-footer.styl
- src/scripts/components/story-footer/story-footer.tsx
- src/scripts/hooks/use-mouse-move.ts
> feat(story-footer): slide in story footer on mouse move

- src/scripts/components/layer-info/layer-info.styl
- src/scripts/components/layer-info/layer-info.tsx
- src/scripts/components/layer-selector/layer-selector.tsx
- storage/layers/layers-de.json
- storage/layers/layers-en.json
> feat(layer-info): use markdown for layer description

- src/scripts/components/globe/globe.tsx
- src/scripts/components/globes/globes.tsx
- storage/layers/layers-de.json
> fix(globe): fix problems with touch devices in compare mode

- src/scripts/components/globe/globe.tsx
- src/scripts/config/main.ts
> feat(globe): use new basemap tiles

- package-lock.json
- src/scripts/components/icons/pause-icon.tsx
- src/scripts/components/time-playback/time-playback.ts
- src/scripts/components/time-slider/time-slider.styl
- src/scripts/components/time-slider/time-slider.tsx
- src/scripts/hooks/use-interval.ts
closes #355 
Without final styles until the new time slider design is implemented.
> feat(time-slider): add playback functionality

- src/scripts/components/globe/globe.tsx
- src/scripts/components/layer-info/layer-info.tsx
- src/scripts/components/story-content/story-content.tsx
set base color (closes #415 )
set link target (closes #416 )
Sorry couldn't keep my fingers off.
> feat(globe): set basecolor

- src/scripts/components/layer-list-item/layer-list-item.tsx
- src/scripts/types/layer-list.d.ts
- storage/layers/layers-de.json
- storage/layers/layers-en.json
> feat(data-set-names): use shortName in layer selector

- src/scripts/components/icons/pause-circle-icon.tsx
- src/scripts/components/icons/play-circle-icon.tsx
- src/scripts/components/time-slider-range/time-slider-range.styl
- src/scripts/components/time-slider-range/time-slider-range.tsx
- src/scripts/components/time-slider/time-slider.styl
- src/scripts/components/time-slider/time-slider.tsx
> feat(time-slider): improve time slider

- i18n/de.json
- i18n/en.json
- i18n/es.json
> refactor(translations): change wording

- src/scripts/components/main/menu/menu.styl
- src/scripts/components/main/menu/menu.tsx
> feat(version): show current version in menu

- src/scripts/components/layers/layer-legend/layer-legend.styl
> refactor(legend): add text shadow

- src/scripts/components/main/icons/change-language-icon.tsx
- src/scripts/components/main/language-bubble/language-bubble.styl
- src/scripts/components/main/language-bubble/language-bubble.tsx
- src/scripts/components/main/navigation/navigation.tsx
> refactor(languageBubble): add icon, close bubble on both options

- src/scripts/components/layers/layer-info/layer-info.styl
> refactor(layer-info): add scrollable content

- src/scripts/components/layers/layer-list-item/layer-list-item.styl
> refactor(layer-list): shorten layer names on hover

- src/scripts/components/layers/data-set-info/data-set-info.styl
> fix(mobile): fix overlapping dataset info on mobile

- src/scripts/hooks/use-globe-layer.ts
- src/scripts/libs/get-image-layer-data.ts
- src/scripts/types/globe-image-layer-data.ts
- src/scripts/types/layer.d.ts
> feat(data-layer): add filter property for client side filtering

- src/scripts/components/layers/layer-legend/layer-legend.tsx
- src/scripts/components/main/data-viewer/data-viewer.tsx
- src/scripts/types/layer.d.ts
> feat(layer-legend): use background color dependent of basemap

- src/scripts/components/layers/time-slider/time-slider.tsx
> feat(globe): stop spinning globe on play

- src/scripts/components/stories/story-list-item/story-list-item.styl
- src/scripts/components/stories/story-list-item/story-list-item.tsx
- src/scripts/components/stories/story-list/story-list.styl
- src/scripts/components/stories/story-tags/story-tags.styl
> feat(story-selector): restyle story images layout

- package.json
> chore(stories-download): do not sync stories-??.json files

- src/scripts/components/main/globe/globe.tsx
> fix(globe): fix strange zoom behaviour

- src/scripts/components/stories/autoplay/autoplay.tsx
- src/scripts/components/stories/story-footer/story-footer.tsx
- src/scripts/components/stories/story-media/story-media.tsx
- src/scripts/components/stories/story/story.tsx
- src/scripts/config/main.ts
- src/scripts/hooks/use-story-navigation.ts
> feat(autoplay-gallery): add autoplay to gallery in showcase mode

- storage/layers/layers-de.json
- storage/layers/layers-en.json
- storage/layers/layers-es.json
- storage/layers/layers-fr.json
- storage/layers/layers-nl.json
> refactor(layer-names): remove asterisk

- src/scripts/components/main/app/app.styl
- src/scripts/components/stories/story-content/story-content.styl
> refactor(scrollbar): set overflow to scroll to avoid weird padding

- src/scripts/components/layers/data-set-info/data-set-info.styl
- src/scripts/components/layers/layer-legend/layer-legend.styl
- src/scripts/components/layers/time-slider/time-slider.styl
> fix(text-select): fix text select when moving globe

- storage/stories/stories-de.json
- storage/stories/stories-en.json
- storage/stories/stories-es.json
- storage/stories/stories-fr.json
- storage/stories/stories-nl.json
- storage/stories/story-30/story-30-de.json
- storage/stories/story-30/story-30-en.json
- storage/stories/story-30/story-30-es.json
- storage/stories/story-30/story-30-fr.json
- storage/stories/story-30/story-30-nl.json
> feat(updateStories): change title images and rename story 30

- src/scripts/components/main/tracking/tracking.tsx
Also track JS errors to Matomo dashboard
closes #467
> feat(tracking): add basic JS error tracking to matomo

- src/scripts/components/layers/time-slider/time-slider.tsx
> refactor(timeslider-labels): respect the dataset specific format

- i18n/de.json
- i18n/en.json
- i18n/es.json
- i18n/fr.json
- i18n/nl.json
- storage/stories/stories-de.json
- storage/stories/stories-en.json
- storage/stories/stories-es.json
- storage/stories/stories-fr.json
- storage/stories/stories-nl.json
> refactor(storySelector): add images, tags and marker position

- src/scripts/components/stories/story-gallery/story-gallery.styl
> refactor(progress): move progress dots higher

- storage/stories/stories-de.json
- storage/stories/stories-en.json
- storage/stories/stories-es.json
> refactor(story-tags): change story tags for urban heat

- src/scripts/components/stories/caption/caption.styl
- src/scripts/components/stories/caption/caption.tsx
- src/scripts/components/stories/layer-description/layer-description.styl
- src/scripts/components/stories/layer-description/layer-description.tsx
- src/scripts/components/stories/story-content/story-content.styl
- src/scripts/components/stories/story-gallery-image/story-gallery-image.styl
- src/scripts/components/stories/story-gallery-image/story-gallery-image.tsx
- src/scripts/components/stories/story-gallery/story-gallery.styl
- src/scripts/components/stories/story-gallery/story-gallery.tsx
- src/scripts/components/stories/story-progress/story-progress.styl
- src/scripts/components/stories/story-progress/story-progress.tsx
closes #883 
closes #884 
closes #885
> refactor(captions): adjust captions depending on imageFit

- src/scripts/components/main/about-project-overlay/about-project-overlay.tsx
- src/scripts/components/main/about-project-standalone/about-project.tsx
- src/scripts/components/main/app/app.styl
- src/scripts/components/main/app/app.tsx
> feat(about): add route for about component

- src/scripts/components/layers/layer-info/layer-info.tsx
- src/scripts/libs/download-screenshot.ts
> refactor(usageInfo): add to layer info, avoid showing the same info

- src/scripts/config/main.ts
Generated tiles from the `satmap-v6-2-4km.tif` file
https://github.com/ubilabs/esa-climate-from-space/issues/1051
> feat(basemap): add new coloured basemap

- src/scripts/libs/download-screenshot.ts
> refactor(downloads): add file extension

- data/downloads/odp-ftp-fire.sh
> feat: add new years to fire dataset

- storage/stories/stories-de.json
- storage/stories/stories-en.json
- storage/stories/stories-es.json
- storage/stories/stories-fr.json
- storage/stories/stories-nl.json
> feat(stories): update story tags

- src/scripts/components/main/globe-navigation/globe-navigation.tsx
- src/scripts/components/main/globe/globe.tsx
> refactor(2D-mode): prevent projection from being cut off after morph

- src/scripts/components/main/navigation/navigation.module.styl
> fix(navigation): add z-index to navigation module

- storage/stories/story-12/story-12-de.json
- storage/stories/story-12/story-12-es.json
- storage/stories/story-12/story-12-fr.json
- storage/stories/story-12/story-12-nl.json
- add iFrame to all languages for story 12
> feat(story-12): add iFrame to all languages

- package-lock.json
- package.json
> feat(globe): update esa-webgl-globe

- src/scripts/components/main/data-viewer/data-viewer.module.styl
> fix(globe): make globe controls clickable

- src/scripts/components/stories/pilot-story/components/01-chapter/01-chapter.tsx
- src/scripts/components/stories/pilot-story/components/globe/globe.module.styl
- src/scripts/components/stories/pilot-story/components/globe/globe.tsx
- src/scripts/components/stories/pilot-story/pilot-story.tsx
- src/scripts/components/stories/pilot-story/types/globe.ts
> feat(pilot-story-globe): move globe down and in

- src/scripts/components/stories/pilot-story/components/globe/globe.tsx
- src/scripts/components/stories/pilot-story/pilot-story.tsx
- src/scripts/components/stories/pilot-story/types/globe.ts
> feat(pilot-story-globe): use xyz coordinates for movements

- package.json
Deployment is already available here:
https://storage.googleapis.com/esa-cfs-versions/web/pilot-story/index.html
> chore(pilot-story): add deployment script

- src/scripts/components/main/app/app.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.tsx
- src/scripts/components/stories/pilot-story/components/chapter-text/chapter-text.module.styl
- src/scripts/components/stories/pilot-story/components/radial-info/radial-info.module.styl
- src/scripts/components/stories/pilot-story/components/radial-info/radial-info.tsx
- src/scripts/components/stories/pilot-story/components/story-intro/story-intro.module.styl
- src/scripts/components/stories/pilot-story/components/story-intro/story-intro.tsx
Add `scroll-snap-align: center` to outer element of a chapter that should be snapped to
> refactor(scroll): snap to chapters

- src/scripts/components/stories/pilot-story/components/02-chapter/02-chapter.tsx
- src/scripts/components/stories/pilot-story/components/explore-dataset/explore-dataset.module.styl
- src/scripts/components/stories/pilot-story/components/explore-dataset/explore-dataset.tsx
- src/scripts/components/stories/pilot-story/pilot-story.tsx
closes #1404
https://github.com/ubilabs/esa-climate-from-space/assets/21622725/dbaf41c3-cd03-4aa0-9080-e04dc7d4736d
> feat(pilot-story): add remaining pages of chapter 2

- src/scripts/components/stories/pilot-story/components/globe/globe.tsx
> feat(pilot-story-globe): update xch4 data layer

- src/scripts/components/stories/pilot-story/components/06-chapter/06-chapter.tsx
- src/scripts/components/stories/pilot-story/components/chapter-video/chapter-video.tsx
closes [#1445](https://github.com/ubilabs/esa-climate-from-space/issues/1445)
> refactor(video): replace and pass videoId

- src/scripts/components/stories/pilot-story/components/01-chapter/01-chapter.tsx
- src/scripts/components/stories/pilot-story/components/02-chapter/02-chapter.tsx
- src/scripts/components/stories/pilot-story/components/03-chapter/03-chapter.tsx
- src/scripts/components/stories/pilot-story/components/04-chapter/04-chapter.tsx
- src/scripts/components/stories/pilot-story/components/05-chapter/05-chapter.tsx
- src/scripts/components/stories/pilot-story/components/06-chapter/06-chapter.tsx
- src/scripts/components/stories/pilot-story/components/07-chapter/07-chapter.module.styl
- src/scripts/components/stories/pilot-story/components/07-chapter/07-chapter.tsx
- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.tsx
- src/scripts/components/stories/pilot-story/components/chapter/chapter.tsx
- src/scripts/components/stories/pilot-story/components/nav-chapter-overview/nav-chapter-overview.tsx
- src/scripts/components/stories/pilot-story/components/story-intro/story-intro.module.styl
- src/scripts/components/stories/pilot-story/components/story-intro/story-intro.tsx
- src/scripts/components/stories/pilot-story/pilot-story.module.styl
- src/scripts/components/stories/pilot-story/pilot-story.tsx
for #1443 
for #1409
- This is the first PR to add scrolling to the navbar. It is missing some implementation details, which will follow.  Also, I refactored the handling of the `onEnter` functionality. 
- adds wrapper for chapter 7
> feat(nav-drawer): add navigation functionality

- src/scripts/components/stories/pilot-story/components/02-chapter/02-chapter.tsx
- src/scripts/components/stories/pilot-story/components/05-chapter/05-chapter.tsx
- src/scripts/components/stories/pilot-story/components/explore-dataset/explore-dataset.module.styl
- src/scripts/components/stories/pilot-story/components/explore-dataset/explore-dataset.tsx
- src/scripts/components/stories/pilot-story/components/globe/globe.tsx
- src/scripts/components/stories/pilot-story/config/main.ts
> feat(pilot-story-explore): add explore dataset to chapter 5

- src/scripts/components/stories/pilot-story/components/02-chapter/02-chapter.module.styl
- src/scripts/components/stories/pilot-story/components/button/button.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-conclusion/chapter-conclusion.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-graph/chapter-graph.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.tsx
- src/scripts/components/stories/pilot-story/components/chapter-text/chapter-text.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-text/chapter-text.tsx
- src/scripts/components/stories/pilot-story/components/chapter-video/chapter-video.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-video/chapter-video.tsx
- src/scripts/components/stories/pilot-story/components/explore-dataset/explore-dataset.module.styl
- src/scripts/components/stories/pilot-story/components/explore-dataset/explore-dataset.tsx
- src/scripts/components/stories/pilot-story/components/explore-stories/explore-stories.module.styl
- src/scripts/components/stories/pilot-story/components/explore-stories/explore-stories.tsx
- src/scripts/components/stories/pilot-story/components/legend/legend.module.styl
- src/scripts/components/stories/pilot-story/components/pilot-carousel/pilot-carousel.module.styl
- src/scripts/components/stories/pilot-story/components/radial-info/radial-info.module.styl
- src/scripts/components/stories/pilot-story/components/radial-info/radial-info.tsx
- src/scripts/components/stories/pilot-story/components/satellite-carousel/satellite-carousel.module.styl
- src/scripts/components/stories/pilot-story/components/scroll-hint/scroll-hint.module.styl
- src/scripts/components/stories/pilot-story/components/snap-wrapper/snap-wrapper.module.styl
- src/scripts/components/stories/pilot-story/components/story-intro/story-intro.module.styl
- src/scripts/components/stories/pilot-story/components/story-intro/story-intro.tsx
first round...
still open: globe movements, more adjustments
> refactor(desktop): adjust ui

- src/scripts/components/stories/pilot-story/components/chapter/chapter.tsx
- src/scripts/components/stories/pilot-story/components/globe/globe.tsx
- src/scripts/components/stories/pilot-story/config/main.ts
- src/scripts/components/stories/pilot-story/provider/globe-provider.tsx
> feat(pilot-story-globe): set data layer per chapter

- src/scripts/components/stories/pilot-story/components/06-chapter/06-chapter.tsx
- src/scripts/components/stories/pilot-story/components/chapter-conclusion/chapter-conclusion.tsx
- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.tsx
- src/scripts/components/stories/pilot-story/components/chapter-markers/chapter-marker.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-markers/chapter-markers.tsx
- src/scripts/components/stories/pilot-story/components/globe/globe.tsx
- src/scripts/components/stories/pilot-story/components/snap-wrapper/snap-wrapper.module.styl
- src/scripts/components/stories/pilot-story/config/main.ts
- src/scripts/components/stories/pilot-story/pilot-story.tsx
> feat(chapter-markers): add back to main story button

- src/scripts/components/stories/pilot-story/components/explore-dataset/explore-dataset.module.styl
- src/scripts/components/stories/pilot-story/components/explore-dataset/explore-dataset.tsx
- src/scripts/components/stories/pilot-story/components/globe/globe.tsx
- src/scripts/components/stories/pilot-story/provider/globe-provider.tsx
- src/scripts/components/stories/story-globe/story-globe.module.styl
- src/scripts/components/stories/story-globe/story-globe.tsx
>  fix(explore-dataset): background color of explorable globe

- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-markers/chapter-marker.module.styl
> fix(chapter-intro): back button not showing

- src/scripts/components/stories/pilot-story/components/explore-stories/explore-stories.module.styl
- src/scripts/components/stories/pilot-story/components/explore-stories/explore-stories.tsx
> fix(explore-titles): fix last chapter

- src/scripts/components/stories/pilot-story/components/04-chapter/04-chapter.tsx
- src/scripts/components/stories/pilot-story/components/satellite-carousel/satellite-carousel.tsx
- src/scripts/components/stories/pilot-story/types/globe.ts
> feat(satllites): adjust names and labels

- src/scripts/components/stories/pilot-story/components/06-chapter/06-chapter.tsx
- src/scripts/components/stories/pilot-story/components/chapter-progress-indication/chapter-progress-indication.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-progress-indication/chapter-progress-indication.tsx
- src/scripts/components/stories/pilot-story/components/chapter/chapter.tsx
- src/scripts/components/stories/pilot-story/components/icons/nav-position-icon/nav-position-icon.tsx
- src/scripts/components/stories/pilot-story/components/nav-chapter-overview/nav-chapter-overview.module.styl
- src/scripts/components/stories/pilot-story/components/nav-chapter-overview/nav-chapter-overview.tsx
- src/scripts/components/stories/pilot-story/components/nav-drawer/nav-drawer.tsx
- src/scripts/components/stories/pilot-story/components/utils/nav-drawer.ts
- src/scripts/components/stories/pilot-story/components/utils/navigation-observer.ts
- src/scripts/components/stories/pilot-story/config/main.ts
- src/scripts/components/stories/pilot-story/hooks/use-chapter-observer.ts
- src/scripts/components/stories/pilot-story/hooks/use-is-in-viewport.ts
- src/scripts/components/stories/pilot-story/pilot-story.tsx
- src/scripts/components/stories/pilot-story/provider/chapter-provider.tsx
- src/scripts/components/stories/pilot-story/types/globe.ts
It will need refactoring when adding more substories. I left comments in the code so we will know
> fea(navigation): add nav for substory

- src/scripts/components/main/icons/expand-icon.tsx
- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.module.styl
- src/scripts/components/stories/pilot-story/components/chapter-intro/chapter-intro.tsx
- src/scripts/components/stories/pilot-story/components/icons/scroll-icon/scroll-icon.tsx
- src/scripts/components/stories/pilot-story/components/scroll-hint/scroll-hint.module.styl
- src/scripts/components/stories/pilot-story/components/scroll-hint/scroll-hint.tsx
> feat(scroll-hint): adjust for desktop

- src/scripts/components/stories/pilot-story/components/button/button.tsx
- src/scripts/components/stories/pilot-story/components/nav-drawer/nav-drawer.tsx
- src/scripts/components/stories/pilot-story/components/story-intro/story-intro.tsx
> feat(link-datasets): link to correct url

- src/scripts/components/stories/pilot-story/components/radial-info/radial-info.tsx
> feat(radial-carousel): reset selected option on exit

- src/scripts/components/stories/pilot-story/components/globe/globe.module.styl
- src/scripts/components/stories/pilot-story/components/nav-chapter-overview/nav-chapter-overview.module.styl
- src/scripts/components/stories/pilot-story/components/nav-drawer/nav-drawer.module.styl
- src/scripts/components/stories/pilot-story/components/nav-drawer/nav-drawer.tsx
- src/scripts/components/stories/pilot-story/components/scroll-hint/scroll-hint.module.styl
> feat(pilot): visual tweaks for globe and text

- src/scripts/components/stories/pilot-story/components/06-chapter/06-chapter.tsx
- src/scripts/components/stories/pilot-story/components/globe/globe.tsx
- src/scripts/components/stories/pilot-story/config/main.ts
fixes globe opacity in chapter 6, when the globe should be at full opacity
> feat(globe): toggle globe opacity

- src/scripts/components/stories/pilot-story/components/explore-dataset/explore-dataset.tsx
> fix(explore-dataset): pilot story globe not showing on chapter change

- src/scripts/components/stories/pilot-story/components/radial-info/radial-info.module.styl
- src/scripts/components/stories/pilot-story/components/radial-info/radial-info.tsx
- src/scripts/components/stories/pilot-story/config/main.ts
> fix(pilot-story-globe): misplaced on radial info screen

- src/scripts/components/stories/pilot-story/components/globe/globe.tsx
> feat(pilot-story-globe): add atmosphere and change spin speed

- src/scripts/components/stories/pilot-story/components/chapter/chapter.tsx
> fix(pilot-story-globe): wrong layers for subchapter

- src/scripts/components/stories/video-js/subtitles.css
- src/scripts/components/stories/video-js/video-js.tsx
closes [1605](https://github.com/ubilabs/esa-climate-from-space/issues/1605)
> feat: improve subtitles

- src/scripts/components/main/data-viewer/data-viewer.module.css
- src/scripts/components/main/globe/globe.module.css
> fix(globe): fix transition between category and conent

- src/scripts/components/main/content-navigation/content-navigation.tsx
- src/scripts/components/main/data-viewer/data-viewer.tsx
- src/scripts/components/main/data-widget/data-widget.tsx
- src/scripts/components/main/globe/globe.tsx
- src/scripts/components/stories/story/story.tsx
- src/scripts/reducers/embed-elements.ts
> feat: add layer preview and story header"

- src/scripts/components/main/app/app.css
- src/scripts/components/main/category-navigation/category-navigation.module.css
- src/scripts/components/main/category-navigation/category-navigation.tsx
- src/scripts/components/main/category-navigation/use-category-event-handlers.ts
- src/scripts/components/main/content-navigation/content-navigation.tsx
- src/scripts/components/main/data-viewer/data-viewer.module.css
- src/scripts/components/main/data-viewer/data-viewer.tsx
- src/scripts/config/main.ts
> style: implement design changes and fix bugs

- src/scripts/components/main/category-navigation/category-navigation.module.css
- src/scripts/components/main/category-navigation/category-navigation.tsx
- src/scripts/components/main/content-navigation/content-navigation.tsx
- src/scripts/components/main/data-viewer/data-viewer.module.css
- src/scripts/components/main/data-viewer/data-viewer.tsx
- src/scripts/components/main/globe/globe.tsx
- src/scripts/components/main/url-sync/url-sync.tsx
- src/scripts/components/stories/story/story.module.css
- src/scripts/components/stories/story/story.tsx
- src/scripts/hooks/use-location.ts
- src/scripts/hooks/use-story-globe.ts
closes #1726 
- refactors how the state of the globe is managed based on the current path
> feat: sync globe state with navigation

- src/scripts/components/main/category-navigation/category-navigation.module.css
- src/scripts/components/main/category-navigation/category-navigation.tsx
- src/scripts/components/main/data-viewer/data-viewer.module.css
- src/scripts/components/main/data-viewer/data-viewer.tsx
closes #1731
- implement design review
- memoize variables in data viewer to avoid re-renders
> feat: implement design review

- src/scripts/components/main/category-navigation/category-navigation.module.css
- src/scripts/components/main/category-navigation/category-navigation.tsx
> feat(category-navigation): add tooltip on hover and focus

- src/scripts/components/main/category-navigation/category-navigation.module.css
- src/scripts/components/main/category-navigation/category-navigation.tsx
- src/scripts/components/main/category-navigation/use-category-event-handlers.ts
- src/scripts/components/main/content-navigation/content-navigation.tsx
- src/scripts/components/main/content-navigation/use-content-event-handlers.ts
- src/scripts/components/main/data-viewer/data-viewer.tsx
- src/scripts/config/main.ts
- src/scripts/hooks/use-auto-content-rotation.ts
> feat(nav): add auto rotate to category nav

- src/scripts/components/main/category-navigation/category-navigation.module.css
- src/scripts/components/main/category-navigation/category-navigation.tsx
- src/scripts/components/main/content-navigation/content-navigation.tsx
> fix: hide tooltip on mobile

- src/scripts/components/layers/time-slider/time-slider.tsx
- src/scripts/components/stories/story-globe/story-globe.tsx
- src/scripts/libs/convert-legacy-story.ts
- src/scripts/types/gallery-item.ts
- src/scripts/types/legacy-story.ts
> feat(story-globe): add on demand layer autoplay

- src/scripts/components/stories/caption/caption.module.css
- src/scripts/components/stories/story-embedded/story-embedded.tsx
- src/scripts/components/stories/story-gallery/story-gallery.module.css
- src/scripts/components/stories/story-gallery/story-gallery.tsx
- src/scripts/components/stories/story-image/story-image.tsx
- src/scripts/components/stories/story-progress/story-progress.module.css
- src/scripts/components/stories/story/story.tsx
> feat(story-image): shrink caption only on mobile

- src/scripts/components/main/category-navigation/category-navigation.tsx
- src/scripts/hooks/use-content-params.ts
> fix: correctly retrieve persisted category

- src/scripts/components/main/embed-checkbox-list/embed-checkbox-list.module.css
- src/scripts/components/main/embed-link-preview/embed-link-preview.module.css
- src/scripts/components/main/embed-result/embed-result.module.css
- src/scripts/components/main/embed-settings/embed-settings.module.css
- src/scripts/components/main/embed-wizard/embed-wizard.module.css
> feat(embed-wizard): make embed wizard mobile friendly

- src/scripts/components/stories/story/blocks/image-gallery/modules/image-compare/image-compare.module.css
- src/scripts/types/story.ts
- storage/stories/debug/debug-en.json
- storage/stories/story-33/story-33-en.json
- small css fixes
- fix `story.ts` types
> fix(story.ts): fix types

- package-lock.json
- package.json
- src/scripts/components/stories/layout/slide-container/slide-container.module.css
- src/scripts/components/stories/story/blocks/generic/text-overlay/text-overlay-slide/text-overlay-slide.module.css
- src/scripts/components/stories/story/blocks/generic/text-overlay/text-overlay.module.css
- src/scripts/components/stories/story/blocks/image-gallery/modules/image-compare/comparison-viewer/comparison-viewer.tsx
- src/scripts/components/stories/story/blocks/image-gallery/modules/image-scroll/image-scroll-image/image-scroll-image.tsx
- src/scripts/components/stories/story/blocks/image-gallery/modules/image-scroll/image-scroll.module.css
- src/scripts/components/stories/story/blocks/splashscreen/splashscreen.module.css
- src/scripts/components/stories/story/story.module.css
- src/scripts/components/stories/story/story.tsx
- src/scripts/config/main.ts
- src/scripts/hooks/use-lenis-for-story.ts
- src/scripts/hooks/use-lenis-toggle.ts
- src/scripts/libs/is-ios-16-or-lower.ts
- src/scripts/providers/story/story-provider.tsx
> feat(story): add and implement smooth scroll via lenis

- src/electron/download-handler.ts
> fix(electron): wrong offline path for dataset downloads

- package-lock.json
- package.json
> chore: update globe version

- README.md
- ci/cloudbuild-electron-builder.yaml
- package-lock.json
- package.json
Cherry-pick of commit for develop.
> chore(build): upload electron build for current version
